version: '3.9'

services:
  db:
    image: postgres:15
    container_name: project_dbcontainer
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: exampass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # <-- external 5433, internal 5432


  backend:
    image: filk1912/gamesplay-backend:latest   # <-- use published image
    container_name: gamesplay-backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn exam_project.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: django-insecure-ol2x@g2v6!n_6jh$5qh-fb$75sdu214da^t=1bq&+7c!($v+cg
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: examdb
      DB_USER: examuser
      DB_PASSWORD: exampass
      DB_HOST: db
      DB_PORT: "5432"

volumes:
  postgres_data:
